# Generated by Django 5.1.6 on 2025-03-25 00:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-date_created"]},
        ),
        migrations.RemoveField(
            model_name="document",
            name="is_received",
        ),
        migrations.RemoveField(
            model_name="document",
            name="is_sent",
        ),
        migrations.AddField(
            model_name="document",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="date_received",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("received", "Received"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("external", "External"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_content",
            field=models.FileField(blank=True, null=True, upload_to="static/files/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_documents",
                to="staffs.userprofile",
            ),
        ),
    ]
