# Generated by Django 5.1.6 on 2025-03-25 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0002_alter_document_options_remove_document_is_received_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_prime_tech", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="document",
            name="recipient_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_outside",
        ),
        migrations.AddField(
            model_name="document",
            name="recipient_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_documents",
                to="staffs.organization",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="sender_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_documents",
                to="staffs.organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="staffs.organization",
            ),
        ),
    ]
