# Generated by Django 5.1.6 on 2025-03-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0003_organization_remove_document_recipient_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, null=True, verbose_name="Summary"),
        ),
    ]
