# Generated by Django 5.1.6 on 2025-03-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0004_document_recipient_name_document_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="method",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Method"
            ),
        ),
    ]
