# Generated by Django 5.1.6 on 2025-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0005_document_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="attachment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Attachment"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="note",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Note"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="page_count",
            field=models.IntegerField(default=1, verbose_name="Page Count"),
        ),
    ]
