# Generated by Django 5.1.6 on 2025-04-07 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0006_document_attachment_document_note_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={},
        ),
        migrations.AddField(
            model_name="document",
            name="status_change_log",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="attachment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_content",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="document",
            name="method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="page_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="document",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="recipient_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_documents",
                to="staffs.organization",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_documents",
                to="staffs.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="sender_organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_documents",
                to="staffs.organization",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
