# Generated by Django 5.2 on 2025-04-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0010_alter_useractionlog_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("role_change", "Role Change"),
                    ("delete", "Delete"),
                    ("send_document", "Send Document"),
                    ("receive_document", "Receive Document"),
                    ("change_document_status", "Change Document Status"),
                    ("delete_document", "Delete Document"),
                    ("update_document_field", "Update Document Field"),
                    ("add_user", "Add User"),
                    ("view_document", "View Document"),
                    ("add_organization", "Add Organization"),
                ],
                max_length=50,
            ),
        ),
    ]
