# Generated by Django 5.2 on 2025-04-27 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0012_chatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="is_support_chat",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="prime_tech_organization",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="secondary_organization",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_support_chat", models.BooleanField(default=False)),
                (
                    "prime_tech_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prime_tech_chats",
                        to="staffs.organization",
                    ),
                ),
                (
                    "secondary_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_chats",
                        to="staffs.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="chat",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="staffs.chat",
            ),
            preserve_default=False,
        ),
    ]
