# Generated by Django 5.2 on 2025-04-28 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0015_alter_chatmessage_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="is_support",
            new_name="is_support_chat",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="name",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="session_key",
        ),
        migrations.AlterField(
            model_name="chat",
            name="secondary_organization",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secondary_chats",
                to="staffs.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
