# Generated by Django 5.2 on 2025-04-28 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0016_rename_is_support_chat_is_support_chat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="sender",
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
