# Generated by Django 5.2 on 2025-05-13 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0018_chat_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Категория"
            ),
        ),
        migrations.AlterField(
            model_name="useractionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("role_change", "Role Change"),
                    ("delete", "Delete"),
                    ("send_document", "Send Document"),
                    ("receive_document", "Receive Document"),
                    ("change_document_status", "Change Document Status"),
                    ("delete_document", "Delete Document"),
                    ("update_document_field", "Update Document Field"),
                    ("add_user", "Add User"),
                    ("view_document", "View Document"),
                    ("add_organization", "Add Organization"),
                    ("create_backup", "Create Backup"),
                    ("download_backup", "Download Backup"),
                    ("restore_backup", "Restore Backup"),
                    ("delete_backup", "Delete Backup"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_data",
                    models.BinaryField(verbose_name="Данные сертификата"),
                ),
                (
                    "private_key",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Закрытый ключ"
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("user", "Пользовательский"),
                            ("ca", "Корневой/промежуточный"),
                        ],
                        default="user",
                        max_length=10,
                        verbose_name="Тип сертификата",
                    ),
                ),
                (
                    "issuer_name",
                    models.CharField(max_length=255, verbose_name="Издатель"),
                ),
                (
                    "subject_name",
                    models.CharField(max_length=255, verbose_name="Субъект"),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Действителен с")),
                ("valid_to", models.DateTimeField(verbose_name="Действителен до")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сертификат",
                "verbose_name_plural": "Сертификаты",
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название шаблона"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("contract", "Договор"),
                            ("memo", "Служебная записка"),
                            ("invoice", "Счет"),
                            ("report", "Отчет"),
                            ("notice", "Уведомление"),
                            ("request", "Заявка"),
                            ("order", "Приказ"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "template_file",
                    models.FileField(
                        upload_to="templates/", verbose_name="Файл шаблона"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Общедоступный"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="staffs.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон документа",
                "verbose_name_plural": "Шаблоны документов",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="staffs.documenttemplate",
                verbose_name="Шаблон",
            ),
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Номер версии"),
                ),
                (
                    "content",
                    models.FileField(upload_to="versions/", verbose_name="Содержимое"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий к версии"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель версии",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="staffs.document",
                        verbose_name="Документ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия документа",
                "verbose_name_plural": "Версии документов",
                "ordering": ["-version_number"],
                "unique_together": {("document", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="DigitalSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature_data", models.BinaryField(verbose_name="Данные подписи")),
                (
                    "signature_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата подписания"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="Действительна"),
                ),
                (
                    "validation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата проверки"
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="staffs.certificate",
                        verbose_name="Сертификат",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="staffs.document",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подписант",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signatures",
                        to="staffs.documentversion",
                        verbose_name="Версия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цифровая подпись",
                "verbose_name_plural": "Цифровые подписи",
            },
        ),
    ]
